firm96 <- read_csv("qy96.csv")
firm97 <- read_csv("qy97.csv")
qy98 <- read_csv("qy98.csv")
firm99 <- read_csv("qy99.csv")
firm00 <- read_csv("qy00.csv")
firm01 <- read_csv("qy01.csv")
firm02 <- read_csv("qy02.csv")
firm03 <- read_csv("qy03.csv")
firm04 <- read_csv("qy04.csv")
firm05 <- read_csv("qy05.csv")
firm06 <- read_csv("qy06.csv")
firm07 <- read_csv("qy07.csv")
firm08 <- read_csv("qy08.csv")
firm09_1 <- read_csv("qy09(1).csv")
firm09_2 <- read_csv("qy09(2).csv")
firm10 <- read_csv("qy10.csv")
firm11 <- read_csv("qy11.csv")
firm12 <- read_csv("qy12.csv")
firm13 <- read_csv("qy13.csv")

firm98 <- firm98 %>% select(c("法人代码","产品销售收入","利润总额","从业人数","实收资本","累计折旧","本年折旧","固定资产合计","流动资产合计","登记注册类型","工业增加值","本年应付工资总额","资产总计"))
names(firm98) <- c("code", "revenue", "profit", "emp", "paidc", "adepre", "cdepre", "nccapital", "ccapital", "type", "va", "wage", "capital")
firm98 <- filter(firm98, !(is.na(revenue)|is.na(emp)|is.na(nccapital)) & emp>8 & capital>nccapital & capital>ccapital & adepre>cdepre & revenue>500 & paidc>0)
write_csv(firm98, "~/Desktop/CHN firms data/firms/firm98.csv")

firm99 <- firm99 %>% select(c("法人代码","产品销售收入","利润总额","全部职工","实收资本","累计折旧","本年折旧","固定资产合计","流动资产合计","注册类型","工业增加值","本年应付工资总额","资产总计"))
names(firm99) <- c("code", "revenue", "profit", "emp", "paidc", "adepre", "cdepre", "nccapital", "ccapital", "type", "va", "wage", "capital")
firm99 <- filter(firm99, !(is.na(revenue)|is.na(emp)|is.na(nccapital)) & emp>8 & capital>nccapital & capital>ccapital & adepre>cdepre & revenue>500 & paidc>0)
write_csv(firm99, "~/Desktop/CHN firms data/firms/firm99.csv")

firm00 <- firm00 %>% select(c("法人代码","销售收入","利润总额","全部职工","实收资本","累计折旧","本年折旧","固定资产合","流动资产计","注册类型","工业增加值","年应付工资","资产总计"))
names(firm00) <- c("code", "revenue", "profit", "emp", "paidc", "adepre", "cdepre", "nccapital", "ccapital", "type", "va", "wage", "capital")
firm00 <- filter(firm00, !(is.na(revenue)|is.na(emp)|is.na(nccapital)) & emp>8 & capital>nccapital & capital>ccapital & adepre>cdepre & revenue>500 & paidc>0)
write_csv(firm00, "~/Desktop/CHN firms data/firms/firm00.csv")

firm01 <- firm01 %>% select(c("法人代码","销售收入","利润总额","全部职工数","实收资本","累计折旧","本年折旧","固定资产","流动资产计",`注册类型　`,"应交增值税","本年工资计","资产总计"))
names(firm01) <- c("code", "revenue", "profit", "emp", "paidc", "adepre", "cdepre", "nccapital", "ccapital", "type", "taxva", "wage", "capital")
firm01 <- filter(firm01, !(is.na(revenue)|is.na(emp)|is.na(nccapital)) & emp>8 & capital>nccapital & capital>ccapital & adepre>cdepre & revenue>500 & paidc>0)
write_csv(firm01, "~/Desktop/CHN firms data/firms/firm01.csv")

firm02 <- firm02 %>% select(c("法人代码","销售收入","利润总额","全部职工数","实收资本","累计折旧","本年折旧","固定资产","流动资产计","注册类型","应交增值税","应付工资","资产总计"))
names(firm02) <- c("code", "revenue", "profit", "emp", "paidc", "adepre", "cdepre", "nccapital", "ccapital", "type", "taxva", "wage", "capital")
firm02 <- filter(firm02, !(is.na(revenue)|is.na(emp)|is.na(nccapital)) & emp>8 & capital>nccapital & capital>ccapital & adepre>cdepre & revenue>500 & paidc>0)
write_csv(firm02, "~/Desktop/CHN firms data/firms/firm02.csv")

firm03 <- firm03 %>% select(c("法人代码","销售收入","利润总额","从业人数","实收资本","累计折旧","本年折旧","固定资产年","流动资产计","注册类型","应交增值税","本工资总额","资产总计"))
names(firm03) <- c("code", "revenue", "profit", "emp", "paidc", "adepre", "cdepre", "nccapital", "ccapital", "type", "taxva", "wage", "capital")
firm03 <- filter(firm03, !(is.na(revenue)|is.na(emp)|is.na(nccapital)) & emp>8 & capital>nccapital & capital>ccapital & adepre>cdepre & revenue>500 & paidc>0)
write_csv(firm03, "~/Desktop/CHN firms data/firms/firm03.csv")

firm04 <- firm04 %>% select(c("法人代码","销项税额","利润总额","全部从业人","实收资本","累计折旧","本年折旧","固定资产合","流动资产合","注册类型","应交增值税","应付工资","资产总计"))
names(firm04) <- c("code", "revenue", "profit", "emp", "paidc", "adepre", "cdepre", "nccapital", "ccapital", "type", "taxva", "wage", "capital")
firm04 <- filter(firm04, !(is.na(revenue)|is.na(emp)|is.na(nccapital)) & emp>8 & capital>nccapital & capital>ccapital & adepre>cdepre & revenue>500 & paidc>0)
write_csv(firm04, "~/Desktop/CHN firms data/firms/firm04.csv")

firm05 <- firm05 %>% select(c("法人代码","销售产值当","利润总额","从业人员总","实收资本","累计折旧","本年折旧","固定资产合","流动资产合","注册类型","应交增值税","应付工资总","资产总计"))
names(firm05) <- c("code", "revenue", "profit", "emp", "paidc", "adepre", "cdepre", "nccapital", "ccapital", "type", "taxva", "wage", "capital")
firm05 <- filter(firm05, !(is.na(revenue)|is.na(emp)|is.na(nccapital)) & emp>8 & capital>nccapital & capital>ccapital & adepre>cdepre & revenue>500 & paidc>0)
write_csv(firm05, "~/Desktop/CHN firms data/firms/firm05.csv")

firm06 <- firm06 %>% select(c("法人代码","销售产值当","利润总额","从业人员","实收资本","累计折旧","本年折旧","固定资产合","流动资产合","注册类型","应交增值税","应付工资","资产总计"))
names(firm06) <- c("code", "revenue", "profit", "emp", "paidc", "adepre", "cdepre", "nccapital", "ccapital", "type", "taxva", "wage", "capital")
firm06 <- filter(firm06, !(is.na(revenue)|is.na(emp)|is.na(nccapital)) & emp>8 & capital>nccapital & capital>ccapital & adepre>cdepre & revenue>500 & paidc>0)
write_csv(firm06, "~/Desktop/CHN firms data/firms/firm06.csv")

firm07 <- firm07 %>% select(c("法人单位代码",`工业销售产值（当年价格）`,"利润总额","年末从业人员合计_总计",`其中：实收资本`,"累计折旧",`其中：本年折旧`,"固定资产合计","流动资产合计","登记注册类型","本年应交增值税",`本年应付工资总额(贷方累计发生额)`,"资产总计"))
names(firm07) <- c("code", "revenue", "profit", "emp", "paidc", "adepre", "cdepre", "nccapital", "ccapital", "type", "taxva", "wage", "capital")
firm07 <- filter(firm07, !(is.na(revenue)|is.na(emp)|is.na(nccapital)) & emp>8 & capital>nccapital & capital>ccapital & adepre>cdepre & revenue>500 & paidc>0)
write_csv(firm07, "~/Desktop/CHN firms data/firms/firm07.csv")

#firm08 無本年折旧
firm08 <- firm08 %>% select(c("法人代码",`工业销售产值(当年价格)`,"利润总额","年末从业人员合计_总计","实收资本","累计折旧","固定资产合计","流动资产合计","登记注册类型","本年应交增值税",`本年应付工资总额(贷方累计发生额)`,"资产总计"))
names(firm08) <- c("code", "revenue", "profit", "emp", "paidc", "adepre", "nccapital", "ccapital", "type", "taxva", "wage", "capital")
firm08 <- filter(firm08, !(is.na(revenue)|is.na(emp)|is.na(nccapital)) & emp>8 & capital>nccapital & capital>ccapital & revenue>500 & paidc>0)
write_csv(firm08, "~/Desktop/CHN firms data/firms/firm08.csv")

firm09_1 <- firm09_1 %>% select(c("法人代码",`工业销售产值(当年价格)`,"利润总额","全部从业人员年平均人数","实收资本","固定资产合计","流动资产合计","登记注册类型","本年应交增值税","资产总计"))
names(firm09_1) <- c("code", "revenue", "profit", "emp", "paidc", "nccapital", "ccapital", "type", "taxva", "capital")
firm09_1 <- filter(firm09_1, !(is.na(revenue)|is.na(emp)|is.na(nccapital)) & emp>8 & capital>nccapital & capital>ccapital & revenue>500 & paidc>0)
write_csv(firm09_1, "~/Desktop/CHN firms data/firms/firm09_1.csv")

firm09_2 <- firm09_2 %>% select(c("法人代码",`工业销售产值(当年价格)`,"利润总额","全部从业人员年平均人数","实收资本","固定资产合计","流动资产合计","登记注册类型","本年应交增值税","资产总计"))
names(firm09_2) <- c("code", "revenue", "profit", "emp", "paidc", "nccapital", "ccapital", "type", "taxva", "capital")
firm09_2 <- filter(firm09_2, !(is.na(revenue)|is.na(emp)|is.na(nccapital)) & emp>8 & capital>nccapital & capital>ccapital & revenue>500 & paidc>0)
write_csv(firm09_2, "~/Desktop/CHN firms data/firms/firm09_2.csv")

#firm010 無本年折旧和应付工资
firm10 <- firm10 %>% select(c("法人代码",`工业销售产值（当年价格）`,"利润总额","年末从业人员合计_总计",`其中：实收资本`,"累计折旧","固定资产合计","流动资产合计","登记注册类型","本年应交增值税","资产总计"))
names(firm10) <- c("code", "revenue", "profit", "emp", "paidc", "adepre", "nccapital", "ccapital", "type", "taxva", "capital")
firm10 <- filter(firm10, !(is.na(revenue)|is.na(emp)|is.na(nccapital)) & emp>8 & capital>nccapital & capital>ccapital & revenue>500 & paidc>0)
write_csv(firm10, "~/Desktop/CHN firms data/firms/firm10.csv")

firm11 <- firm11 %>% select(c("组织机构代码","工业销售产值","利润总额","从业人数",`其中：实收资本`,"累计折旧",`其中：本年折旧`,"固定资产合计","流动资产合计","登记注册类型","应交增值税","应付职工薪酬","资产总计"))
names(firm11) <- c("code", "revenue", "profit", "emp", "paidc", "adepre", "cdepre", "nccapital", "ccapital", "type", "taxva", "wage", "capital")
firm11 <- filter(firm11, !(is.na(revenue)|is.na(emp)|is.na(nccapital)) & emp>8 & capital>nccapital & capital>ccapital & adepre>cdepre & revenue>500 & paidc>0)
write_csv(firm11, "~/Desktop/CHN firms data/firms/firm11.csv")

firm12 <- firm12 %>% select(c(`_组织机构代码`,"工业销售产值_当年价格_","利润总额",`_从业人数`,`其中：实收资本`,"累计折旧",`其中：本年折旧`,"固定资产合计","流动资产合计","登记注册类型","应交增值税","应付职工薪酬_本年贷方累计发生额_","资产总计"))
names(firm12) <- c("code", "revenue", "profit", "emp", "paidc", "adepre", "cdepre", "nccapital", "ccapital", "type", "taxva", "wage", "capital")
firm12 <- filter(firm12, !(is.na(revenue)|is.na(emp)|is.na(nccapital)) & emp>8 & capital>nccapital & capital>ccapital & adepre>cdepre & revenue>500 & paidc>0)
write_csv(firm12, "~/Desktop/CHN firms data/firms/firm12.csv")

firm13 <- firm13 %>% select(c(`_组织机构代码`,"工业销售产值","利润总额",`_从业人数`,"实收资本","累计折旧","本年折旧","固定资产合计","流动资产合计","登记注册类型","应交增值税","应付职工薪酬","资产总计"))
names(firm13) <- c("code", "revenue", "profit", "emp", "paidc", "adepre", "cdepre", "nccapital", "ccapital", "type", "taxva", "wage", "capital")
firm13 <- filter(firm13, !(is.na(revenue)|is.na(emp)|is.na(nccapital)) & emp>8 & capital>nccapital & capital>ccapital & adepre>cdepre & revenue>500 & paidc>0)
write_csv(firm13, "~/Desktop/CHN firms data/firms/firm13.csv")
